# Site settings
name: Dzplus
email: Dzplus@163.com
author: Dzplus
url: https://dzplus.github.io/
resume_site: https://dzplus.github.io/
github: https://github.com/dzplus
baseurl: "/Dzplus"
description: Be Care !
meta_description: 瞎鸡儿写
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: dzplus

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

